import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'PhoneNAS 1.0.2 beta', description: 'Turn selected Android storage into practical SMB network shares.' };

export default function PhoneNAS() {
  return <>
    <section className="product-spotlight nas-spotlight"><div><span className="status">1.0.2 beta · Android</span><div className="product-lockup"><img src="/phonenas/icon.png" alt="" /><span>PhoneNAS</span></div><h1>Your spare phone has storage. Put it to work.</h1><p className="lede">Share selected Android folders and attached storage with computers on your trusted local network using familiar SMB access, users and permissions.</p><p className="product-safety-link">Want to know how PhoneNAS handles storage, access and privacy? <a href="/privacy/#phonenas">Read privacy &amp; safety →</a></p><div className="actions"><a className="button" href="/files/PhoneNAS-1.0.2-Android.apk" download>Download Android APK</a><a href="#connect">Mac helper and direct SMB ↓</a></div><p className="helper-note"><strong>Files stay on your local network.</strong> PhoneNAS does not require a Jenux Labs account or cloud file relay.</p></div><div className="phone-stage nas-phone-stage"><figure><img src="/phonenas/home-093.png" alt="PhoneNAS running on Android" /></figure><span className="float-tag online">● NAS running</span><span className="float-tag speed">SMB · local network</span></div></section>
    <section className="signal-strip"><span>ANDROID STORAGE</span><span>STANDARD SMB</span><span>MULTIPLE SHARES</span><span>USERS + HOME FOLDERS</span></section>
    <section className="section"><header><p className="eyebrow">A PHONE-SIZED NAS</p><h2>Share only what you choose.</h2><p>PhoneNAS is built around explicit folders and named users, not an all-or-nothing view of the phone.</p></header><div className="feature-grid"><article><b>01</b><h3>Phone and attached storage</h3><p>Share folders such as Downloads or DCIM and supported attached drives, subject to Android’s storage access rules.</p></article><article><b>02</b><h3>Multiple named shares</h3><p>Give each selected folder a clear SMB share name and manage it independently.</p></article><article><b>03</b><h3>Users and private homes</h3><p>Control share access and optionally give each user a quota-managed home folder.</p></article><article><b>04</b><h3>App or local web controls</h3><p>Manage status, users, storage, logs, network trash and settings from the phone or local web management.</p></article></div></section>
    <section className="privacy-band"><div><p className="eyebrow">SAFE LOCAL FILE MANAGEMENT</p><h2>Fast moves. Optional recovery.</h2></div><div><p>Folder moves within the same share stay on the storage instead of making a computer round trip.</p><p>Optional network trash can retain deleted files for the period you choose, or remain disabled when immediate deletion is preferred.</p></div></section>
    <section className="section app-screens"><header><p className="eyebrow">THE REAL APP</p><h2>Status and storage, clearly separated.</h2><p>Start or stop the NAS, inspect recent devices, manage folders and open the detailed controls when needed.</p></header><div className="screen-gallery nas-gallery"><figure><img src="/phonenas/home-093.png" alt="PhoneNAS main status screen" /><figcaption>NAS status, devices and management</figcaption></figure><figure><img src="/phonenas/overview.jpg" alt="PhoneNAS status overview" /><figcaption>Running status and shared storage</figcaption></figure><figure><img src="/phonenas/shares.jpg" alt="PhoneNAS shared folders" /><figcaption>Multiple selected folders and shares</figcaption></figure></div></section>
    <section className="connect-band" id="connect"><div><p className="eyebrow">CONNECT YOUR WAY</p><h2>Helper or direct SMB.</h2></div><div className="connect-options"><article><span>01</span><h3>Use the Mac helper</h3><p>The helper discovers available PhoneNAS devices, makes them visible in Finder and relays SMB locally while it is running.</p><a className="button" href="/files/PhoneNAS-Helper-1.3-macOS.dmg" download>Download Mac helper 1.3</a></article><article><span>02</span><h3>Connect directly</h3><p>Use Finder’s Connect to Server or your computer’s normal network-drive tools with the address shown in PhoneNAS.</p><code>smb://username@phone-ip:4445/share</code><p>The helper is optional. Finder or Windows handles the password and file transfer.</p></article></div></section>
    <section className="safety-note"><strong>Keep it local.</strong><p>PhoneNAS is intended for trusted local networks. Do not expose its SMB or web-management ports directly to the internet. The Mac helper is Developer ID signed, notarized by Apple and contains no telemetry or cloud service.</p></section>
  </>;
}
