const apps = [
  { name: 'PhoneDrop', status: 'Available', tone: 'drop', line: 'Move files directly between Android, macOS and Windows.', detail: 'Fast local transfers. No account, no cloud detour.', href: '/products/phonedrop/', icon: '/phonedrop/logo.png' },
  { name: 'PhoneNAS', status: '1.0.2 beta', tone: 'nas', line: 'Turn an Android phone into useful network storage.', detail: 'Folders, attached drives, users and permissions over familiar SMB.', href: '/products/phonenas/', icon: '/phonenas/icon.png' },
  { name: 'MindGallery', status: 'Android beta', tone: 'mind', line: 'A gallery that can actually help you find things.', detail: 'Local-first search, OCR and careful people review, built on Aves.', href: '/products/mindgallery/', icon: '/mindgallery/icon.png' },
  { name: 'P-CAM', status: 'Android + Mac preview', tone: 'cam', line: 'A small camera crew made from the phones you already own.', detail: 'Record locally. Monitor and direct together over your own Wi-Fi.', href: '/products/pcam/', icon: '/pcam/icon.png' },
];

export default function Home() {
  return <>
    <section className="home-hero"><div className="home-copy"><p className="eyebrow">JENUX LABS · USEFUL TECHNOLOGY</p><h1>Make your devices do more.</h1><p className="lede">Practical software that connects phones and computers, keeps simple jobs simple, and puts useful hardware back to work.</p><div className="actions"><a className="button" href="/products/">Explore products</a><a href="/about/">About Jenux Labs →</a></div></div><div className="hero-stack" aria-label="PhoneDrop and PhoneNAS screenshots"><figure className="hero-phone hero-phone-back"><img src="/phonenas/home-093.png" alt="PhoneNAS running on Android" /></figure><figure className="hero-phone hero-phone-front"><img src="/phonedrop/speed.jpg" alt="PhoneDrop transferring a file on Android" /></figure><span className="hero-chip hero-chip-local">LOCAL-FIRST</span><span className="hero-chip hero-chip-three">ANDROID · MAC · WINDOWS</span></div></section>
    <section className="signal-strip"><span>DIRECT TRANSFERS</span><span>LOCAL STORAGE</span><span>NO REQUIRED ACCOUNT</span><span>BUILT INDEPENDENTLY</span></section>
    <section className="app-showcase" id="apps"><header><p className="eyebrow">THE PRODUCTS</p><h2>Four useful things.<br />No fake roadmap.</h2><p>Stable software, real beta builds and honest previews—each labelled for what it is today.</p></header><div className="app-grid">{apps.map((app) => <a className={`app-card ${app.tone}`} href={app.href} key={app.name}><div className="app-card-top"><img src={app.icon} alt="" /><span className="status">{app.status}</span></div><h3>{app.name}</h3><p className="app-line">{app.line}</p><p>{app.detail}</p><strong>See {app.name} <span>↗</span></strong></a>)}</div></section>
    <section className="home-feature home-feature-drop"><div><p className="eyebrow">PHONEDROP</p><h2>The shortest path between your devices.</h2><p className="large">Choose files, pick a trusted device, and watch them move directly across your local network.</p><a className="text-arrow" href="/products/phonedrop/">See PhoneDrop and downloads →</a></div><div className="feature-screen-row"><figure><img src="/phonedrop/devices.jpg" alt="PhoneDrop nearby devices" /></figure><figure><img src="/phonedrop/activity.jpg" alt="PhoneDrop recent activity" /></figure></div></section>
    <section className="home-feature home-feature-nas"><div className="feature-screen-row"><figure><img src="/phonenas/overview.jpg" alt="PhoneNAS overview" /></figure><figure><img src="/phonenas/shares.jpg" alt="PhoneNAS shared folders" /></figure></div><div><p className="eyebrow">PHONENAS · 1.0.2 BETA</p><h2>A useful second life for spare storage.</h2><p className="large">Choose folders, create users and connect with normal SMB from the computers you already use.</p><a className="text-arrow" href="/products/phonenas/">Get PhoneNAS and the Mac helper →</a></div></section>
    <section className="home-notes"><header><p className="eyebrow">LAB NOTES</p><h2>How the work gets made.</h2><p>Short notes from inside the lab—what shipped, what is still rough, and why the products work the way they do.</p></header><div className="note-grid"><a href="/blog/why-local-first/"><span>11 OCT 2026 · 3 MIN</span><h3>Local-first is a practical choice</h3><p>Fewer detours, fewer accounts, and devices talking directly when they can.</p><strong>Read note →</strong></a><a href="/blog/old-devices-new-jobs/"><span>11 OCT 2026 · 3 MIN</span><h3>Old devices, new jobs</h3><p>A spare phone can be storage, a camera, or part of a useful little system.</p><strong>Read note →</strong></a><a href="/blog/what-beta-means/"><span>11 OCT 2026 · 2 MIN</span><h3>What beta means here</h3><p>Real packages, honest labels, and no pretending the unfinished parts are done.</p><strong>Read note →</strong></a></div><a className="text-arrow" href="/blog/">All lab notes →</a></section>
    <section className="principles"><div><b>01</b><strong>Useful first</strong><p>Focused tools for real jobs.</p></div><div><b>02</b><strong>Local by design</strong><p>Direct routes where they make sense.</p></div><div><b>03</b><strong>Independent</strong><p>Practical engineering without invented hype.</p></div></section>
  </>;
}
